import { boot } from '@seiza/web/bootstrap';
import fontUrl from '@seiza/web/fonts/IBMPlexSans-Regular.ttf?url';
// Generated by wasm-bindgen into web/pkg/ (gitignored); `just tycho dev` builds it.
import init, { start } from '../pkg/tycho.js';
// The same asset wasm-bindgen would resolve; named here so the HTML preload and
// `init` fetch one URL (instantiateStreaming needs `application/wasm`).
import wasmUrl from '../pkg/tycho_bg.wasm?url';
import { createBridge } from './bridge.ts';

const bridge = createBridge();
// `?bench`: the perf scripts query the same engine the app uses (row counts,
// paging experiments), and read the app's wasm memory to check the perf
// panel's. The bridge loads nothing until its first call.
const bench = new URLSearchParams(location.search).has('bench');
if (bench) (globalThis as { __tychoBridge?: typeof bridge }).__tychoBridge = bridge;

const instantiate = async () => {
  const exports = await init({ module_or_path: wasmUrl });
  if (bench) (globalThis as { __tychoWasmMemory?: WebAssembly.Memory }).__tychoWasmMemory = exports.memory;
  return exports;
};
void boot({ init: instantiate, start: (font) => start(font, bridge), fontUrl, wasmUrl });
